### ISSUE TITLE
Keyrunner Uninstalling from User Computers

### ISSUE THREAD

**Issue by Mayo-API-Management** [launchiamenterprise/keyrunner#92] opened 2024-10-28 14:26 UTC
**Describe the bug**
Users are reporting Keyrunner being randomly uninstalled/removed from their Windows computers. 

We are unable to find any event logs where the MSIInstaller was removed. 
 
We are wondering if this could be caused by a failed update or it uninstalled itself for some reason.

**Comment by launchiamenterprise** [comment] 2024-10-28 15:18
@Mayo-API-Management Thanks for letting us know about the removals. To help us resolve this quickly, could you provide a few more details?

1) Approximately how many users have experienced Keyrunner being removed?
2) Are there any Group Policies in place?
3) Have any endpoint protection tools flagged Keyrunner or did users receive any security prompts when the removal happened?

Generally a failed update should not automatically uninstall the application and we are actively investigating this scenario

**Comment by launchiamenterprise** [comment] 2024-10-29 16:56
We will monitor this issue closely and with our upcoming release we will introduce detailed logging for both updates and any potential failures. This will help us narrow down the root cause of the problem if one exists. As of now we haven't observed this issue with any other users or within our internal team. Please let us know if this happens again with any other users.

**Comment by launchiamenterprise** [comment] 2024-10-30 17:59
Thanks for letting us know! We actually fixed an auto-update bug(https://github.com/launchiamenterprise/keyrunner/issues/50) in our previous release, so with the new .exe file, you shouldn’t run into this issue again. 

Also as stated above we will introduce additional logging for updates and potential failures. Closing this issue for now. please reopen this issue if it happens again.

**Closed by launchiamenterprise** 2024-10-30 17:59 UTC
